### ISSUE TITLE
python3.9 报错了

### ISSUE THREAD

**Issue by wbteve** [Litt1eQ/aliyundrive-api#1]
PS D:\Project\pythonPro\aliyundrive-api>  python index.py  ./config.ini
Traceback (most recent call last):
  File "D:\Project\pythonPro\aliyundrive-api\index.py", line 299, in <module>
    api = AliyunDriveApi()
  File "D:\Project\pythonPro\aliyundrive-api\index.py", line 70, in __init__
    self.get_user_info()
  File "D:\Project\pythonPro\aliyundrive-api\index.py", line 94, in get_user_info
    if self.do_refresh_token():
  File "D:\Project\pythonPro\aliyundrive-api\index.py", line 78, in do_refresh_token
    res = requests.post("https://websv.aliyundrive.com/token/refresh", headers={
  File "C:\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by anonymous-qsh** [comment]
> PS D:\Project\pythonPro\aliyundrive-api> python index.py ./config.ini
> Traceback (most recent call last):
> File "D:\Project\pythonPro\aliyundrive-api\index.py", line 299, in
> api = AliyunDriveApi()
> File "D:\Project\pythonPro\aliyundrive-api\index.py", line 70, in **init**
> self.get_user_info()
> File "D:\Project\pythonPro\aliyundrive-api\index.py", line 94, in get_user_info
> if self.do_refresh_token():
> File "D:\Project\pythonPro\aliyundrive-api\index.py", line 78, in do_refresh_token
> res = requests.post("https://websv.aliyundrive.com/token/refresh", headers={
> File "C:\Python39\lib\site-packages\requests\models.py", line 900, in json
> return complexjson.loads(self.text, **kwargs)
> File "C:\Python39\lib\json__init__.py", line 346, in loads
> return _default_decoder.decode(s)
> File "C:\Python39\lib\json\decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

您好，请检查您的access_token和refresh_token是否按照配置正确填写。

**Comment by Litt1eQ** [comment]
> PS D:\Project\pythonPro\aliyundrive-api> python index.py ./config.ini
> Traceback (most recent call last):
> File "D:\Project\pythonPro\aliyundrive-api\index.py", line 299, in 
> api = AliyunDriveApi()
> File "D:\Project\pythonPro\aliyundrive-api\index.py", line 70, in **init**
> self.get_user_info()
> File "D:\Project\pythonPro\aliyundrive-api\index.py", line 94, in get_user_info
> if self.do_refresh_token():
> File "D:\Project\pythonPro\aliyundrive-api\index.py", line 78, in do_refresh_token
> res = requests.post("https://websv.aliyundrive.com/token/refresh", headers={
> File "C:\Python39\lib\site-packages\requests\models.py", line 900, in json
> return complexjson.loads(self.text, **kwargs)
> File "C:\Python39\lib\json__init__.py", line 346, in loads
> return _default_decoder.decode(s)
> File "C:\Python39\lib\json\decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

您好，请检查一下access_token和refresh_token是否按照配置填写。
